name: cynic
description: >
  Utilities for offline-first development.
version: 0.1.2
authors:
  - Matan Lurey <matanl@google.com>
  - Robert Felker <felker.robert@gmail.com>
homepage: https://github.com/matanlurey/cynic

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  meta: ^1.0.5

dev_dependencies:
  test: # REPLACE_ME
